spring:
  flyway:
    locations: "classpath:/db/migration/mysql"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:todos}"
    username: "${MYSQL_USER:user1}"
    password: "${MYSQL_PASSWORD:mysql123}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"