spring:
  application:
    name: todos-mysql
  flyway:
    locations: 'classpath:/db/migration/h2'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
todos:
  mysql:
    limit: 1024