spring:
  application:
    name: todos-mysql
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: "*"
todos:
  api:
    limit: 1024
  ids:
    tinyId: true